### ISSUE TITLE
singer-check-tap error codes

### ISSUE THREAD

**Issue by btwq** [singer-io/getting-started#40]
Hi Singer,

When running singer-check-tap, I am getting 

`ERROR: tap exited with status 255`

Where can i get a listing of these status codes? Thanks

**Comment by cmerrick** [comment]
Hi @btwq there are no special status codes associated with Singer, other than the standard Linux practice of exiting 0 on success and non-zero on failure.  For exit status 255, that's coming from the python runtime, either because it caught a signal or because it ran into a fatal error.  In either case, I would expect the tap's logs to give you some indication about why it happened.
